spring:
  application:
    name: item-service
    
#server:
#  port: 8001

eureka:
  client:
    service-url:
      #默认位置，可以修改为具体地理位置，比如：beiJing, shangHai, shenZhen 等，表示 eureka 服务器的部署位置
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

---
spring:
  profiles: item1

server:
  port: 8001
---
spring:
  profiles: item2
  
server:
  port: 8002

