spring:
  application:
    name: order-service
    
  rabbitmq:
    host: 192.168.149.132
    port: 5672
    username: admin
    password: admin
    
#server:
#  port: 8201

eureka:
  client:
    service-url:
      #默认位置，可以修改为具体地理位置，比如：beiJing, shangHai, shenZhen 等，表示 eureka 服务器的部署位置
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
feign:
  hystrix:
    enabled: true
    
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        
---
spring:
  profiles: order1
  
server:
  port: 8201

---      
spring:
  profiles: order2
  
server:
  port: 8202
      
      
      
      
      
      
      

      